import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

MIN_SEQ_LEN = 3
MAX_SEQ_LEN = 10
NUM_RANGE = (0, 100)
NUM_BINS = 101

TRAIN_SAMPLES = 100000
VAL_SAMPLES = 12000
TEST_SAMPLES = 5000

BATCH_SIZE = 256
NUM_EPOCHS = 20
LEARNING_RATE = 1e-4

D_MODEL = 128
NHEAD = 4
NUM_ENCODER_LAYERS = 3
NUM_DECODER_LAYERS = 3
DIM_FEEDFORWARD = 512
DROPOUT = 0.1

SOS_TOKEN = NUM_BINS
EOS_TOKEN = NUM_BINS + 1
PAD_TOKEN = NUM_BINS + 2
VOCAB_SIZE = NUM_BINS + 3

PLOT_DIR = "plots"
MODEL_DIR = "models"
MODEL_PATH = f"{MODEL_DIR}/sort_transformer.pt"
